POST http://localhost:8080/api/v1/companies
content-type: application/json

{
    "name": "Created",
    "address": "Testaddress",
    "country": "AUT"
}

###
PUT http://localhost:8080/api/v1/companies/13
content-type: application/json

{
    "name": "Updated",
    "address": "Testaddress",
    "country": "AUT"
}

###
DELETE  http://localhost:8080/api/v1/companies/7
content-type: application/json

###
GET http://localhost:8080/api/v1/companies


###
GET http://localhost:8080/api/v1/companies/employee/1